// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Shield_information_barrier_segment_restrictions
{
    /// <summary>The type of the shield barrier segmentrestriction for this member.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Shield_information_barrier_segment_restrictionsPostRequestBody_type
    {
        [EnumMember(Value = "shield_information_barrier_segment_restriction")]
        #pragma warning disable CS1591
        Shield_information_barrier_segment_restriction,
        #pragma warning restore CS1591
    }
}
