// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension
{
    /// <summary>
    /// Builds and executes requests for operations under \files\{file_id}\thumbnail.{extension}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThumbnailWithExtensionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="extension">The file format for the thumbnail.</param>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThumbnailWithExtensionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter, string extension = "") : base(requestAdapter, "{+baseurl}/files/{file_id}/thumbnail.{extension}{?max_height*,max_width*,min_height*,min_width*}", pathParameters)
        {
            if (!string.IsNullOrWhiteSpace(extension)) PathParameters.Add("extension", extension);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ThumbnailWithExtensionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/files/{file_id}/thumbnail.{extension}{?max_height*,max_width*,min_height*,min_width*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a thumbnail, or smaller image representation, of a file.Sizes of `32x32`,`64x64`, `128x128`, and `256x256` can be returned inthe `.png` format and sizes of `32x32`, `160x160`, and `320x320`can be returned in the `.jpg` format.Thumbnails can be generated for the image and video file formats listed[found on our community site][1].[1]: https://community.box.com/t5/Migrating-and-Previewing-Content/File-Types-and-Fonts-Supported-in-Box-Content-Preview/ta-p/327
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder.ThumbnailWithExtensionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder.ThumbnailWithExtensionRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a thumbnail, or smaller image representation, of a file.Sizes of `32x32`,`64x64`, `128x128`, and `256x256` can be returned inthe `.png` format and sizes of `32x32`, `160x160`, and `320x320`can be returned in the `.jpg` format.Thumbnails can be generated for the image and video file formats listed[found on our community site][1].[1]: https://community.box.com/t5/Migrating-and-Previewing-Content/File-Types-and-Fonts-Supported-in-Box-Content-Preview/ta-p/327
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder.ThumbnailWithExtensionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder.ThumbnailWithExtensionRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "image/jpg, image/png, application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.Files.Item.ThumbnailWithExtension.ThumbnailWithExtensionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a thumbnail, or smaller image representation, of a file.Sizes of `32x32`,`64x64`, `128x128`, and `256x256` can be returned inthe `.png` format and sizes of `32x32`, `160x160`, and `320x320`can be returned in the `.jpg` format.Thumbnails can be generated for the image and video file formats listed[found on our community site][1].[1]: https://community.box.com/t5/Migrating-and-Previewing-Content/File-Types-and-Fonts-Supported-in-Box-Content-Preview/ta-p/327
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ThumbnailWithExtensionRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum height of the thumbnail.</summary>
            [QueryParameter("max_height")]
            public int? MaxHeight { get; set; }
            /// <summary>The maximum width of the thumbnail.</summary>
            [QueryParameter("max_width")]
            public int? MaxWidth { get; set; }
            /// <summary>The minimum height of the thumbnail.</summary>
            [QueryParameter("min_height")]
            public int? MinHeight { get; set; }
            /// <summary>The minimum width of the thumbnail.</summary>
            [QueryParameter("min_width")]
            public int? MinWidth { get; set; }
        }
    }
}
#pragma warning restore CS0618
