// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Group_memberships
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Group_membershipsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Custom configuration for the permissions an adminif a group will receive. This option has no effecton members with a role of `member`.Setting these permissions overwrites the defaultaccess levels of an admin.Specifying a value of `null` for this object will disableall configurable permissions. Specifying permissions will setthem accordingly, omitted permissions will be enabled by default.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_configurable_permissions? ConfigurablePermissions { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_configurable_permissions ConfigurablePermissions { get; set; }
#endif
        /// <summary>The group to add the user to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_group? Group { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_group Group { get; set; }
#endif
        /// <summary>The role of the user in the group.</summary>
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_role? Role { get; set; }
        /// <summary>The user to add to the group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_user? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody"/> and sets the default values.
        /// </summary>
        public Group_membershipsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configurable_permissions", n => { ConfigurablePermissions = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_configurable_permissions>(global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_configurable_permissions.CreateFromDiscriminatorValue); } },
                { "group", n => { Group = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_group>(global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_group.CreateFromDiscriminatorValue); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_role>(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_user>(global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_configurable_permissions>("configurable_permissions", ConfigurablePermissions);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_group>("group", Group);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_role>("role", Role);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Group_memberships.Group_membershipsPostRequestBody_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
