// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.Oauth2.TokenRefresh
{
    /// <summary>
    /// Builds and executes requests for operations under \oauth2\token#refresh
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokenRefreshRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Oauth2.TokenRefresh.TokenRefreshRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRefreshRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2/token#refresh", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Oauth2.TokenRefresh.TokenRefreshRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokenRefreshRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2/token#refresh", rawUrl)
        {
        }
        /// <summary>
        /// Refresh an Access Token using its client ID, secret, and refresh token.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.AccessToken"/></returns>
        /// <param name="body">A request to refresh an Access Token. Use this API to refresh an expiredAccess Token using a valid Refresh Token.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.OAuth2Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.OAuth2Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.AccessToken?> PostAsync(global::Soenneker.Box.OpenApiClient.Models.PostOAuth2TokenRefreshAccessToken body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.AccessToken> PostAsync(global::Soenneker.Box.OpenApiClient.Models.PostOAuth2TokenRefreshAccessToken body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Box.OpenApiClient.Models.OAuth2Error.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.OAuth2Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.AccessToken>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.AccessToken.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Refresh an Access Token using its client ID, secret, and refresh token.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">A request to refresh an Access Token. Use this API to refresh an expiredAccess Token using a valid Refresh Token.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Box.OpenApiClient.Models.PostOAuth2TokenRefreshAccessToken body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Box.OpenApiClient.Models.PostOAuth2TokenRefreshAccessToken body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Oauth2.TokenRefresh.TokenRefreshRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.Oauth2.TokenRefresh.TokenRefreshRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.Oauth2.TokenRefresh.TokenRefreshRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
