// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.Events
{
    /// <summary>
    /// Builds and executes requests for operations under \events
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events{?created_after*,created_before*,event_type,limit*,stream_position*,stream_type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events{?created_after*,created_before*,event_type,limit*,stream_position*,stream_type*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns up to a year of past events for a given useror for the entire enterprise.By default this returns events for the authenticated user. To retrieve eventsfor the entire enterprise, set the `stream_type` to `admin_logs_streaming`for live monitoring of new events, or `admin_logs` for querying acrosshistorical events. The user making the API call willneed to have admin privileges, and the application will need to have thescope `manage enterprise properties` checked.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Events"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Events?> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Events> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.Events>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.Events.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of real-time servers that can be used for long-polling updatesto the [event stream](https://developer.box.com/reference/get-events).Long polling is the concept where a HTTP request is kept open until theserver sends a response, then repeating the process over and over to receiveupdated responses.Long polling the event stream can only be used for user events, not forenterprise events.To use long polling, first use this endpoint to retrieve a list of long pollURLs. Next, make a long poll request to any of the provided URLs.When an event occurs in monitored account a response with the value`new_change` will be sent. The response contains no other details asit only serves as a prompt to take further action such as sending arequest to the [events endpoint](https://developer.box.com/reference/get-events) with the last known`stream_position`.After the server sends this response it closes the connection. You must nowrepeat the long poll process to begin listening for events again.If no events occur for a while and the connection times out you willreceive a response with the value `reconnect`. When you receive this responseyou’ll make another call to this endpoint to restart the process.If you receive no events in `retry_timeout` seconds then you will need tomake another request to the real-time server (one of the URLs in the responsefor this endpoint). This might be necessary due to network errors.Finally, if you receive a `max_retries` error when making a request to thereal-time server, you should start over by making a call to this endpointfirst.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.RealtimeServers"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.RealtimeServers?> OptionsAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.RealtimeServers> OptionsAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToOptionsRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.RealtimeServers>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.RealtimeServers.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns up to a year of past events for a given useror for the entire enterprise.By default this returns events for the authenticated user. To retrieve eventsfor the entire enterprise, set the `stream_type` to `admin_logs_streaming`for live monitoring of new events, or `admin_logs` for querying acrosshistorical events. The user making the API call willneed to have admin privileges, and the application will need to have thescope `manage enterprise properties` checked.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a list of real-time servers that can be used for long-polling updatesto the [event stream](https://developer.box.com/reference/get-events).Long polling is the concept where a HTTP request is kept open until theserver sends a response, then repeating the process over and over to receiveupdated responses.Long polling the event stream can only be used for user events, not forenterprise events.To use long polling, first use this endpoint to retrieve a list of long pollURLs. Next, make a long poll request to any of the provided URLs.When an event occurs in monitored account a response with the value`new_change` will be sent. The response contains no other details asit only serves as a prompt to take further action such as sending arequest to the [events endpoint](https://developer.box.com/reference/get-events) with the last known`stream_position`.After the server sends this response it closes the connection. You must nowrepeat the long poll process to begin listening for events again.If no events occur for a while and the connection times out you willreceive a response with the value `reconnect`. When you receive this responseyou’ll make another call to this endpoint to restart the process.If you receive no events in `retry_timeout` seconds then you will need tomake another request to the real-time server (one of the URLs in the responsefor this endpoint). This might be necessary due to network errors.Finally, if you receive a `max_retries` error when making a request to thereal-time server, you should start over by making a call to this endpointfirst.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToOptionsRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToOptionsRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.OPTIONS, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.Events.EventsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns up to a year of past events for a given useror for the entire enterprise.By default this returns events for the authenticated user. To retrieve eventsfor the entire enterprise, set the `stream_type` to `admin_logs_streaming`for live monitoring of new events, or `admin_logs` for querying acrosshistorical events. The user making the API call willneed to have admin privileges, and the application will need to have thescope `manage enterprise properties` checked.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderGetQueryParameters 
        {
            /// <summary>The lower bound date and time to return events for. This can only be usedwhen requesting the events with a `stream_type` of `admin_logs`. For anyother `stream_type` this value will be ignored.</summary>
            [QueryParameter("created_after")]
            public DateTimeOffset? CreatedAfter { get; set; }
            /// <summary>The upper bound date and time to return events for. This can only be usedwhen requesting the events with a `stream_type` of `admin_logs`. For anyother `stream_type` this value will be ignored.</summary>
            [QueryParameter("created_before")]
            public DateTimeOffset? CreatedBefore { get; set; }
            /// <summary>A comma-separated list of events to filter by. This can only be used whenrequesting the events with a `stream_type` of `admin_logs` or`adming_logs_streaming`. For any other `stream_type` this value will beignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event_type")]
            public global::Soenneker.Box.OpenApiClient.Events.GetEvent_typeQueryParameterType[]? EventType { get; set; }
#nullable restore
#else
            [QueryParameter("event_type")]
            public global::Soenneker.Box.OpenApiClient.Events.GetEvent_typeQueryParameterType[] EventType { get; set; }
#endif
            /// <summary>Limits the number of events returned.Note: Sometimes, the events less than the limit requested can be returnedeven when there may be more events remaining. This is primarily done inthe case where a number of events have already been retrieved and theseretrieved events are returned rather than delaying for an unknown amountof time to see if there are any more results.</summary>
            [QueryParameter("limit")]
            public long? Limit { get; set; }
            /// <summary>The location in the event stream to start receiving events from.* `now` will return an empty list events andthe latest stream position for initialization.* `0` or `null` will return all events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("stream_position")]
            public string? StreamPosition { get; set; }
#nullable restore
#else
            [QueryParameter("stream_position")]
            public string StreamPosition { get; set; }
#endif
            /// <summary>Defines the type of events that are returned* `all` returns everything for a user and is the default* `changes` returns events that may cause file tree changes  such as file updates or collaborations.* `sync` is similar to `changes` but only applies to synced folders* `admin_logs` returns all events for an entire enterprise and  requires the user making the API call to have admin permissions. This  stream type is for programmatically pulling from a 1 year history of  events across all users within the enterprise and within a  `created_after` and `created_before` time frame. The complete history  of events will be returned in chronological order based on the event  time, but latency will be much higher than `admin_logs_streaming`.* `admin_logs_streaming` returns all events for an entire enterprise and  requires the user making the API call to have admin permissions. This  stream type is for polling for recent events across all users within  the enterprise. Latency will be much lower than `admin_logs`, but  events will not be returned in chronological order and may  contain duplicates.</summary>
            [QueryParameter("stream_type")]
            public global::Soenneker.Box.OpenApiClient.Events.GetStream_typeQueryParameterType? StreamType { get; set; }
        }
    }
}
#pragma warning restore CS0618
