// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo
{
    /// <summary>
    /// Builds and executes requests for operations under \folders\{folder_id}\metadata\enterprise\securityClassification-6VMVochwUWo
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SecurityClassification6VMVochwUWoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecurityClassification6VMVochwUWoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/folders/{folder_id}/metadata/enterprise/securityClassification-6VMVochwUWo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SecurityClassification6VMVochwUWoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/folders/{folder_id}/metadata/enterprise/securityClassification-6VMVochwUWo", rawUrl)
        {
        }
        /// <summary>
        /// Removes any classifications from a folder.This API can also be called by including the enterprise ID in theURL explicitly, for example`/folders/:id/enterprise_12345/securityClassification-6VMVochwUWo`.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the classification metadata instance thathas been applied to a folder.This API can also be called by including the enterprise ID in theURL explicitly, for example`/folders/:id/enterprise_12345/securityClassification-6VMVochwUWo`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Classification"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Classification?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Classification> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.Classification>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.Classification.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Adds a classification to a folder by specifying the label of theclassification to add.This API can also be called by including the enterprise ID in theURL explicitly, for example`/folders/:id/enterprise_12345/securityClassification-6VMVochwUWo`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Classification"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Classification?> PostAsync(global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Classification> PostAsync(global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.Classification>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.Classification.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates a classification on a folder.The classification can only be updated if a classification has already beenapplied to the folder before. When editing classifications, only values aredefined for the enterprise will be accepted.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Classification"/></returns>
        /// <param name="body">A list containing the one change to make, toupdate the classification label.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Classification?> PutAsync(List<global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWo> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Classification> PutAsync(List<global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWo> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.Classification>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.Classification.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Removes any classifications from a folder.This API can also be called by including the enterprise ID in theURL explicitly, for example`/folders/:id/enterprise_12345/securityClassification-6VMVochwUWo`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Retrieves the classification metadata instance thathas been applied to a folder.This API can also be called by including the enterprise ID in theURL explicitly, for example`/folders/:id/enterprise_12345/securityClassification-6VMVochwUWo`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Adds a classification to a folder by specifying the label of theclassification to add.This API can also be called by including the enterprise ID in theURL explicitly, for example`/folders/:id/enterprise_12345/securityClassification-6VMVochwUWo`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Updates a classification on a folder.The classification can only be updated if a classification has already beenapplied to the folder before. When editing classifications, only values aredefined for the enterprise will be accepted.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">A list containing the one change to make, toupdate the classification label.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(List<global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWo> body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(List<global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWo> body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json-patch+json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo.SecurityClassification6VMVochwUWoRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
