// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Folders.Item.Metadata.Enterprise.SecurityClassification6VMVochwUWo
{
    /// <summary>Defines classificationsavailable in the enterprise.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SecurityClassification6VMVochwUWo_path
    {
        [EnumMember(Value = "/Box__Security__Classification__Key")]
        #pragma warning disable CS1591
        Box__Security__Classification__Key,
        #pragma warning restore CS1591
    }
}
