// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Models;
using Soenneker.Box.OpenApiClient.Storage_policy_assignments.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.Storage_policy_assignments
{
    /// <summary>
    /// Builds and executes requests for operations under \storage_policy_assignments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Storage_policy_assignmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Box.OpenApiClient.storage_policy_assignments.item collection</summary>
        /// <param name="position">The ID of the storage policy assignment.</param>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Item.WithStorage_policy_assignment_ItemRequestBuilder"/></returns>
        public global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Item.WithStorage_policy_assignment_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("storage_policy_assignment_id", position);
                return new global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Item.WithStorage_policy_assignment_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Storage_policy_assignmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/storage_policy_assignments?resolved_for_id={resolved_for_id}&resolved_for_type={resolved_for_type}{&marker*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Storage_policy_assignmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/storage_policy_assignments?resolved_for_id={resolved_for_id}&resolved_for_type={resolved_for_type}{&marker*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetches all the storage policy assignment for an enterprise or user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignments"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignments?> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder.Storage_policy_assignmentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignments> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder.Storage_policy_assignmentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignments>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignments.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a storage policy assignment for an enterprise or user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignment"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignment?> PostAsync(global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignment> PostAsync(global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignment>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.StoragePolicyAssignment.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetches all the storage policy assignment for an enterprise or user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder.Storage_policy_assignmentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder.Storage_policy_assignmentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a storage policy assignment for an enterprise or user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/storage_policy_assignments", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.Storage_policy_assignmentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetches all the storage policy assignment for an enterprise or user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Storage_policy_assignmentsRequestBuilderGetQueryParameters 
        {
            /// <summary>Defines the position marker at which to begin returning results. This isused when paginating using marker-based pagination.This requires `usemarker` to be set to `true`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("marker")]
            public string? Marker { get; set; }
#nullable restore
#else
            [QueryParameter("marker")]
            public string Marker { get; set; }
#endif
            /// <summary>The ID of the user or enterprise to return assignments for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("resolved_for_id")]
            public string? ResolvedForId { get; set; }
#nullable restore
#else
            [QueryParameter("resolved_for_id")]
            public string ResolvedForId { get; set; }
#endif
            /// <summary>The target type to return assignments for.</summary>
            [QueryParameter("resolved_for_type")]
            public global::Soenneker.Box.OpenApiClient.Storage_policy_assignments.GetResolved_for_typeQueryParameterType? ResolvedForType { get; set; }
        }
    }
}
#pragma warning restore CS0618
