// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Storage_policy_assignments
{
    /// <summary>The type to assign.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Storage_policy_assignmentsPostRequestBody_storage_policy_type
    {
        [EnumMember(Value = "storage_policy")]
        #pragma warning disable CS1591
        Storage_policy,
        #pragma warning restore CS1591
    }
}
