// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields
{
    /// <summary>
    /// Builds and executes requests for operations under \metadata_templates\{namespace-id}\{template_key}\fields
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FieldsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Box.OpenApiClient.metadata_templates.item.item.fields.item collection</summary>
        /// <param name="position">The key of the metadata taxonomy field in the template.</param>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields.Item.WithField_keyItemRequestBuilder"/></returns>
        public global::Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields.Item.WithField_keyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("field_key", position);
                return new global::Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields.Item.WithField_keyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metadata_templates/{namespace%2Did}/{template_key}/fields", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Metadata_templates.Item.Item.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metadata_templates/{namespace%2Did}/{template_key}/fields", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
