// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Metadata_templates.Schema
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SchemaPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether or not to copy any metadata attached to a file or folderwhen it is copied. By default, metadata is not copied along with afile or folder when it is copied.</summary>
        public bool? CopyInstanceOnItemCopy { get; set; }
        /// <summary>The display name of the template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>An ordered list of template fields which are part of the template.Each field can be a regular text field, date field, number field,as well as a single or multi-select list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody_fields>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody_fields> Fields { get; set; }
#endif
        /// <summary>Defines if this template is visible in the Box web app UI, or ifit is purely intended for usage through the API.</summary>
        public bool? Hidden { get; set; }
        /// <summary>The scope of the metadata template to create. Applications canonly create templates for use within the authenticated user&apos;senterprise.This value needs to be set to `enterprise`, as `global` scopes cannot be created by applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scope { get; set; }
#nullable restore
#else
        public string Scope { get; set; }
#endif
        /// <summary>A unique identifier for the template. This identifier needs to beunique across the enterprise for which the metadata template isbeing created.When not provided, the API will create a unique `templateKey`based on the value of the `displayName`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateKey { get; set; }
#nullable restore
#else
        public string TemplateKey { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody"/> and sets the default values.
        /// </summary>
        public SchemaPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "copyInstanceOnItemCopy", n => { CopyInstanceOnItemCopy = n.GetBoolValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody_fields>(global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody_fields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "scope", n => { Scope = n.GetStringValue(); } },
                { "templateKey", n => { TemplateKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("copyInstanceOnItemCopy", CopyInstanceOnItemCopy);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Metadata_templates.Schema.SchemaPostRequestBody_fields>("fields", Fields);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteStringValue("scope", Scope);
            writer.WriteStringValue("templateKey", TemplateKey);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
