// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Metadata_templates.Schema
{
    /// <summary>The type of field. The basic fields are a `string` field for text, a`float` field for numbers, and a `date` field to present the user with adate-time picker.Additionally, metadata templates support an `enum` field for a basic listof items, and ` multiSelect` field for a similar list of items where theuser can select more than one value.Metadata taxonomies are also supported as a `taxonomy` field type with a specific set of additional properties, which describe its structure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SchemaPostRequestBody_fields_type
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "float")]
        #pragma warning disable CS1591
        Float,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "enum")]
        #pragma warning disable CS1591
        Enum,
        #pragma warning restore CS1591
        [EnumMember(Value = "multiSelect")]
        #pragma warning disable CS1591
        MultiSelect,
        #pragma warning restore CS1591
        [EnumMember(Value = "taxonomy")]
        #pragma warning disable CS1591
        Taxonomy,
        #pragma warning restore CS1591
    }
}
