// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Files.Item
{
    /// <summary>Defines who is allowed to download this file. The possiblevalues are either `open` for everyone or `company` forthe other members of the user&apos;s enterprise.This setting overrides the download permissions that arenormally part of the `role` of a collaboration. When set to`company`, this essentially removes the download option forexternal users with `viewer` or `editor` a roles.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithFile_PutRequestBody_permissions_can_download
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "company")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
    }
}
