// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Files.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithFile_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of collections to make this filea member of. Currentlywe only support the `favorites` collection.To get the ID for a collection, use the[List all collections][1] endpoint.Passing an empty array `[]` or `null` will removethe file from all collections.[1]: https://developer.box.com/reference/get-collections</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_collections>? Collections { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_collections> Collections { get; set; }
#endif
        /// <summary>The description for a file. This can be seen in the right-hand sidebar panelwhen viewing a file in the Box web app. Additionally, this index is used inthe search index of the file, allowing users to find the file by the contentin the description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The retention expiration timestamp for the given file. Thisdate cannot be shortened once set on a file.</summary>
        public DateTimeOffset? DispositionAt { get; set; }
        /// <summary>Defines a lock on an item. This prevents the item from beingmoved, renamed, or otherwise changed by anyone other than the userwho created the lock.Set this to `null` to remove the lock.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_lock? Lock { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_lock Lock { get; set; }
#endif
        /// <summary>An optional different name for the file. This can be used torename the file.File names must be unique within their parent folder. The name check is case-insensitive, so a filenamed `New File` cannot be created in a parent folder that already contains a folder named `new file`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_parent? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_parent Parent { get; set; }
#endif
        /// <summary>Defines who can download a file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_permissions? Permissions { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_permissions Permissions { get; set; }
#endif
        /// <summary>The shared_link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_shared_link? SharedLink { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_shared_link SharedLink { get; set; }
#endif
        /// <summary>The tags for this item. These tags are shown inthe Box web app and mobile apps next to an item.To add or remove a tag, retrieve the item&apos;s current tags,modify them, and then update this field.There is a limit of 100 tags per item, and 10,000unique tags per enterprise.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithFile_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collections", n => { Collections = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_collections>(global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_collections.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "disposition_at", n => { DispositionAt = n.GetDateTimeOffsetValue(); } },
                { "lock", n => { Lock = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_lock>(global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_lock.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_parent>(global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_parent.CreateFromDiscriminatorValue); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_permissions>(global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_permissions.CreateFromDiscriminatorValue); } },
                { "shared_link", n => { SharedLink = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_shared_link>(global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_shared_link.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_collections>("collections", Collections);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("disposition_at", DispositionAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_lock>("lock", Lock);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_parent>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_permissions>("permissions", Permissions);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Files.Item.WithFile_PutRequestBody_shared_link>("shared_link", SharedLink);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
