// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.File_version_legal_holds.Item;
using Soenneker.Box.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.File_version_legal_holds
{
    /// <summary>
    /// Builds and executes requests for operations under \file_version_legal_holds
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class File_version_legal_holdsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Box.OpenApiClient.file_version_legal_holds.item collection</summary>
        /// <param name="position">The ID of the file version legal hold.</param>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.File_version_legal_holds.Item.WithFile_version_legal_hold_ItemRequestBuilder"/></returns>
        public global::Soenneker.Box.OpenApiClient.File_version_legal_holds.Item.WithFile_version_legal_hold_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("file_version_legal_hold_id", position);
                return new global::Soenneker.Box.OpenApiClient.File_version_legal_holds.Item.WithFile_version_legal_hold_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public File_version_legal_holdsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/file_version_legal_holds?policy_id={policy_id}{&limit*,marker*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public File_version_legal_holdsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/file_version_legal_holds?policy_id={policy_id}{&limit*,marker*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of file versions on legal hold for a legal holdassignment.Due to ongoing re-architecture efforts this API might not return all fileversions for this policy ID.Instead, this API will only return file versions held in the legacyarchitecture. Two new endpoints will available to request any file versionsheld in the new architecture.For file versions held in the new architecture, the `GET/legal_hold_policy_assignments/:id/file_versions_on_hold` API can be used toreturn all past file versions available for this policy assignment, and the`GET /legal_hold_policy_assignments/:id/files_on_hold` API can be used toreturn any current (latest) versions of a file under legal hold.The `GET /legal_hold_policy_assignments?policy_id={id}` API can be used tofind a list of policy assignments for a given policy ID.Once the re-architecture is completed this API will be deprecated.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.FileVersionLegalHolds"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.FileVersionLegalHolds?> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder.File_version_legal_holdsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.FileVersionLegalHolds> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder.File_version_legal_holdsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.FileVersionLegalHolds>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.FileVersionLegalHolds.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of file versions on legal hold for a legal holdassignment.Due to ongoing re-architecture efforts this API might not return all fileversions for this policy ID.Instead, this API will only return file versions held in the legacyarchitecture. Two new endpoints will available to request any file versionsheld in the new architecture.For file versions held in the new architecture, the `GET/legal_hold_policy_assignments/:id/file_versions_on_hold` API can be used toreturn all past file versions available for this policy assignment, and the`GET /legal_hold_policy_assignments/:id/files_on_hold` API can be used toreturn any current (latest) versions of a file under legal hold.The `GET /legal_hold_policy_assignments?policy_id={id}` API can be used tofind a list of policy assignments for a given policy ID.Once the re-architecture is completed this API will be deprecated.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder.File_version_legal_holdsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder.File_version_legal_holdsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.File_version_legal_holds.File_version_legal_holdsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of file versions on legal hold for a legal holdassignment.Due to ongoing re-architecture efforts this API might not return all fileversions for this policy ID.Instead, this API will only return file versions held in the legacyarchitecture. Two new endpoints will available to request any file versionsheld in the new architecture.For file versions held in the new architecture, the `GET/legal_hold_policy_assignments/:id/file_versions_on_hold` API can be used toreturn all past file versions available for this policy assignment, and the`GET /legal_hold_policy_assignments/:id/files_on_hold` API can be used toreturn any current (latest) versions of a file under legal hold.The `GET /legal_hold_policy_assignments?policy_id={id}` API can be used tofind a list of policy assignments for a given policy ID.Once the re-architecture is completed this API will be deprecated.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class File_version_legal_holdsRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of items to return per page.</summary>
            [QueryParameter("limit")]
            public long? Limit { get; set; }
            /// <summary>Defines the position marker at which to begin returning results. This isused when paginating using marker-based pagination.This requires `usemarker` to be set to `true`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("marker")]
            public string? Marker { get; set; }
#nullable restore
#else
            [QueryParameter("marker")]
            public string Marker { get; set; }
#endif
            /// <summary>The ID of the legal hold policy to get the file version legalholds for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("policy_id")]
            public string? PolicyId { get; set; }
#nullable restore
#else
            [QueryParameter("policy_id")]
            public string PolicyId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
