// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Files.WithFile_idAdd_shared_link
{
    /// <summary>The level of access for the shared link. This can berestricted to anyone with the link (`open`), only peoplewithin the company (`company`) and only those whohave been invited to the file (`collaborators`).If not set, this field defaults to the access level specifiedby the enterprise admin. To create a shared link with thisdefault setting pass the `shared_link` object withno `access` field, for example `{ &quot;shared_link&quot;: {} }`.The `company` access level is only available to paidaccounts.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithFile_idAdd_shared_linkPutRequestBody_shared_link_access
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "company")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "collaborators")]
        #pragma warning disable CS1591
        Collaborators,
        #pragma warning restore CS1591
    }
}
