// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTrash_contentQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "non_trashed_only")]
        #pragma warning disable CS1591
        Non_trashed_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "trashed_only")]
        #pragma warning disable CS1591
        Trashed_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "all_items")]
        #pragma warning disable CS1591
        All_items,
        #pragma warning restore CS1591
    }
}
