// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Tasks.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTask_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action the task assignee will be prompted to do. Must be* `review` defines an approval task that can be approved orrejected,* `complete` defines a general task which can be completed.</summary>
        public global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody_action? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defines which assignees need to complete this task before the taskis considered completed.* `all_assignees` (default) requires all assignees to review orapprove the task in order for it to be considered completed.* `any_assignee` accepts any one assignee to review orapprove the task in order for it to be considered completed.</summary>
        public global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody_completion_rule? CompletionRule { get; set; }
        /// <summary>When the task is due at.</summary>
        public DateTimeOffset? DueAt { get; set; }
        /// <summary>The message included with the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithTask_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody_action>(); } },
                { "completion_rule", n => { CompletionRule = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody_completion_rule>(); } },
                { "due_at", n => { DueAt = n.GetDateTimeOffsetValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody_action>("action", Action);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Tasks.Item.WithTask_PutRequestBody_completion_rule>("completion_rule", CompletionRule);
            writer.WriteDateTimeOffsetValue("due_at", DueAt);
            writer.WriteStringValue("message", Message);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
