// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Box.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Retention_policies
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Retention_policiesPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether owner and co-owners of a file are notifiedwhen the policy nears expiration.</summary>
        public bool? AreOwnersNotified { get; set; }
        /// <summary>Whether the owner of a file will be allowed toextend the retention.</summary>
        public bool? CanOwnerExtendRetention { get; set; }
        /// <summary>A list of users notified whenthe retention policy duration is about to end.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.UserMini>? CustomNotificationRecipients { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.UserMini> CustomNotificationRecipients { get; set; }
#endif
        /// <summary>The additional text description of the retention policy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The disposition action of the retention policy.`permanently_delete` deletes the contentretained by the policy permanently.`remove_retention` lifts retention policyfrom the content, allowing it to be deletedby users once the retention policy has expired.</summary>
        public global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_disposition_action? DispositionAction { get; set; }
        /// <summary>The name for the retention policy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyName { get; set; }
#nullable restore
#else
        public string PolicyName { get; set; }
#endif
        /// <summary>The type of the retention policy. A retentionpolicy type can either be `finite`, where aspecific amount of time to retain the content is knownupfront, or `indefinite`, where the amount of timeto retain the content is still unknown.</summary>
        public global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_policy_type? PolicyType { get; set; }
        /// <summary>The length of the retention policy. This valuespecifies the duration in days that the retentionpolicy will be active for after being assigned tocontent.  If the policy has a `policy_type` of`indefinite`, the `retention_length` will also be`indefinite`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length? RetentionLength { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length RetentionLength { get; set; }
#endif
        /// <summary>Specifies the retention type:* `modifiable`: You can modify the retention policy. For example,you can add or remove folders, shorten or lengthenthe policy duration, or delete the assignment.Use this type if your retention policyis not related to any regulatory purposes.* `non_modifiable`: You can modify the retention policyonly in a limited way: add a folder, lengthen the duration,retire the policy, change the disposition actionor notification settings. You cannot perform other actions,such as deleting the assignment or shortening thepolicy duration. Use this type to ensurecompliance with regulatory retention policies.</summary>
        public global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_retention_type? RetentionType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody"/> and sets the default values.
        /// </summary>
        public Retention_policiesPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "are_owners_notified", n => { AreOwnersNotified = n.GetBoolValue(); } },
                { "can_owner_extend_retention", n => { CanOwnerExtendRetention = n.GetBoolValue(); } },
                { "custom_notification_recipients", n => { CustomNotificationRecipients = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "disposition_action", n => { DispositionAction = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_disposition_action>(); } },
                { "policy_name", n => { PolicyName = n.GetStringValue(); } },
                { "policy_type", n => { PolicyType = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_policy_type>(); } },
                { "retention_length", n => { RetentionLength = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length>(global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length.CreateFromDiscriminatorValue); } },
                { "retention_type", n => { RetentionType = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_retention_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("are_owners_notified", AreOwnersNotified);
            writer.WriteBoolValue("can_owner_extend_retention", CanOwnerExtendRetention);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.UserMini>("custom_notification_recipients", CustomNotificationRecipients);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_disposition_action>("disposition_action", DispositionAction);
            writer.WriteStringValue("policy_name", PolicyName);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_policy_type>("policy_type", PolicyType);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length>("retention_length", RetentionLength);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody_retention_type>("retention_type", RetentionType);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Retention_policiesPostRequestBody_retention_length : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Box.OpenApiClient.Retention_policies.Retention_policiesPostRequestBody.Retention_policiesPostRequestBody_retention_length();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
