// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Retention_policy_assignments
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Retention_policy_assignmentsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The item to assign the policy to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_assign_to? AssignTo { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_assign_to AssignTo { get; set; }
#endif
        /// <summary>If the `assign_to` type is `metadata_template`,then optionally add the `filter_fields` parameter which willrequire an array of objects with a field entry and a value entry.Currently only one object of `field` and `value` is supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_filter_fields>? FilterFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_filter_fields> FilterFields { get; set; }
#endif
        /// <summary>The ID of the retention policy to assign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PolicyId { get; set; }
#nullable restore
#else
        public string PolicyId { get; set; }
#endif
        /// <summary>The date the retention policy assignment begins.If the `assigned_to` type is `metadata_template`,this field can be a date field&apos;s metadata attribute key id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDateField { get; set; }
#nullable restore
#else
        public string StartDateField { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody"/> and sets the default values.
        /// </summary>
        public Retention_policy_assignmentsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assign_to", n => { AssignTo = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_assign_to>(global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_assign_to.CreateFromDiscriminatorValue); } },
                { "filter_fields", n => { FilterFields = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_filter_fields>(global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_filter_fields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "policy_id", n => { PolicyId = n.GetStringValue(); } },
                { "start_date_field", n => { StartDateField = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_assign_to>("assign_to", AssignTo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Retention_policy_assignments.Retention_policy_assignmentsPostRequestBody_filter_fields>("filter_fields", FilterFields);
            writer.WriteStringValue("policy_id", PolicyId);
            writer.WriteStringValue("start_date_field", StartDateField);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
