// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Folders.Item
{
    /// <summary>Specifies whether a folder should be synced to auser&apos;s device or not. This is used by Box Sync(discontinued) and is not used by Box Drive.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithFolder_PutRequestBody_sync_state
    {
        [EnumMember(Value = "synced")]
        #pragma warning disable CS1591
        Synced,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_synced")]
        #pragma warning disable CS1591
        Not_synced,
        #pragma warning restore CS1591
        [EnumMember(Value = "partially_synced")]
        #pragma warning disable CS1591
        Partially_synced,
        #pragma warning restore CS1591
    }
}
