// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Folders.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithFolder_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies if users who are not the ownerof the folder can invite new collaborators to the folder.</summary>
        public bool? CanNonOwnersInvite { get; set; }
        /// <summary>Restricts collaborators who are not the owner ofthis folder from viewing other collaborations onthis folder.It also restricts non-owners from inviting newcollaborators.When setting this field to `false`, it is requiredto also set `can_non_owners_invite_collaborators` to`false` if it has not already been set.</summary>
        public bool? CanNonOwnersViewCollaborators { get; set; }
        /// <summary>An array of collections to make this foldera member of. Currentlywe only support the `favorites` collection.To get the ID for a collection, use the[List all collections][1] endpoint.Passing an empty array `[]` or `null` will removethe folder from all collections.[1]: https://developer.box.com/reference/get-collections</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_collections>? Collections { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_collections> Collections { get; set; }
#endif
        /// <summary>The optional description of this folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The folder_upload_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_folder_upload_email? FolderUploadEmail { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_folder_upload_email FolderUploadEmail { get; set; }
#endif
        /// <summary>Specifies if new invites to this folder are restricted to userswithin the enterprise. This does not affect existingcollaborations.</summary>
        public bool? IsCollaborationRestrictedToEnterprise { get; set; }
        /// <summary>The optional new name for this folder.The following restrictions to folder names apply: names containingnon-printable ASCII characters, forward and backward slashes(`/`, `\`), names with trailing spaces, and names `.` and `..` arenot allowed.Folder names must be unique within their parent folder. The name check is case-insensitive,so a folder named `New Folder` cannot be created in a parent folder that already containsa folder named `new folder`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_parent? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_parent Parent { get; set; }
#endif
        /// <summary>The shared_link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_shared_link? SharedLink { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_shared_link SharedLink { get; set; }
#endif
        /// <summary>Specifies whether a folder should be synced to auser&apos;s device or not. This is used by Box Sync(discontinued) and is not used by Box Drive.</summary>
        public global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_sync_state? SyncState { get; set; }
        /// <summary>The tags for this item. These tags are shown inthe Box web app and mobile apps next to an item.To add or remove a tag, retrieve the item&apos;s current tags,modify them, and then update this field.There is a limit of 100 tags per item, and 10,000unique tags per enterprise.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithFolder_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "can_non_owners_invite", n => { CanNonOwnersInvite = n.GetBoolValue(); } },
                { "can_non_owners_view_collaborators", n => { CanNonOwnersViewCollaborators = n.GetBoolValue(); } },
                { "collections", n => { Collections = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_collections>(global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_collections.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "folder_upload_email", n => { FolderUploadEmail = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_folder_upload_email>(global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_folder_upload_email.CreateFromDiscriminatorValue); } },
                { "is_collaboration_restricted_to_enterprise", n => { IsCollaborationRestrictedToEnterprise = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_parent>(global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_parent.CreateFromDiscriminatorValue); } },
                { "shared_link", n => { SharedLink = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_shared_link>(global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_shared_link.CreateFromDiscriminatorValue); } },
                { "sync_state", n => { SyncState = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_sync_state>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("can_non_owners_invite", CanNonOwnersInvite);
            writer.WriteBoolValue("can_non_owners_view_collaborators", CanNonOwnersViewCollaborators);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_collections>("collections", Collections);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_folder_upload_email>("folder_upload_email", FolderUploadEmail);
            writer.WriteBoolValue("is_collaboration_restricted_to_enterprise", IsCollaborationRestrictedToEnterprise);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_parent>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_shared_link>("shared_link", SharedLink);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Folders.Item.WithFolder_PutRequestBody_sync_state>("sync_state", SyncState);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
