// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Webhooks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhooksPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The URL that is notified by this webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>The item that will trigger the webhook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_target? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_target Target { get; set; }
#endif
        /// <summary>An array of event names that this webhook isto be triggered for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_triggers?>? Triggers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_triggers?> Triggers { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody"/> and sets the default values.
        /// </summary>
        public WebhooksPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_target>(global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_target.CreateFromDiscriminatorValue); } },
                { "triggers", n => { Triggers = n.GetCollectionOfEnumValues<global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_triggers>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_target>("target", Target);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Box.OpenApiClient.Webhooks.WebhooksPostRequestBody_triggers>("triggers", Triggers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
