// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Collaborations.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithCollaboration_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Determines if the invited users can see the entire parent path tothe associated folder. The user will not gain privileges in anyparent folder and therefore can not see content the user is notcollaborated on.Be aware that this meaningfully increases the time required to load theinvitee&apos;s **All Files** page. We recommend you limit the number ofcollaborations with `can_view_path` enabled to 1,000 per user.Only an owner or co-owners can invite collaborators with a `can_view_path` of`true`. Only an owner can update `can_view_path` on existing collaborations.`can_view_path` can only be used for folder collaborations.When you delete a folder with `can_view_path=true`, collaborators may still see the parent path. For instructions on how to remove this, see [Even though a folder invited via can_view_path is deleted, the path remains displayed](https://support.box.com/hc/en-us/articles/37472814319891-Even-though-a-folder-invited-via-can-view-path-is-deleted-the-path-remains-displayed).</summary>
        public bool? CanViewPath { get; set; }
        /// <summary>Update the expiration date for the collaboration. At this date,the collaboration will be automatically removed from the item.This feature will only work if the **Automatically remove invitedcollaborators: Allow folder owners to extend the expiry date**setting has been enabled in the **Enterprise Settings**of the **Admin Console**. When the setting is not enabled,collaborations can not have an expiry date and a value for thisfield will be result in an error.Additionally, a collaboration can only be given anexpiration if it was created after the **Automatically removeinvited collaborator** setting was enabled.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The level of access granted.</summary>
        public global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody_role? Role { get; set; }
        /// <summary>Set the status of a `pending` collaboration invitation,effectively accepting, or rejecting the invite.</summary>
        public global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithCollaboration_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "can_view_path", n => { CanViewPath = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody_role>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("can_view_path", CanViewPath);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody_role>("role", Role);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Collaborations.Item.WithCollaboration_PutRequestBody_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
