// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The type of AI agent used to handle queries.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiAgentAsk_type
    {
        [EnumMember(Value = "ai_agent_ask")]
        #pragma warning disable CS1591
        Ai_agent_ask,
        #pragma warning restore CS1591
    }
}
