// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// AI agent processor used to handle basic text.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiAgentBasicTextToolTextGen : global::Soenneker.Box.OpenApiClient.Models.AiAgentBasicTextToolBase, IParsable
    {
        /// <summary>The prompt template contains contextual information of the request and the user prompt.When using the `prompt_template` parameter, you **must include** input for `{user_question}`.Inputs for `{current_date}` and `{content}` are optional, depending on the use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PromptTemplate { get; set; }
#nullable restore
#else
        public string PromptTemplate { get; set; }
#endif
        /// <summary>System messages aim at helping the LLM understand its role and what it is supposed to do.The input for `{current_date}` is optional, depending on the use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemMessage { get; set; }
#nullable restore
#else
        public string SystemMessage { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.AiAgentBasicTextToolTextGen"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Box.OpenApiClient.Models.AiAgentBasicTextToolTextGen CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.AiAgentBasicTextToolTextGen();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "prompt_template", n => { PromptTemplate = n.GetStringValue(); } },
                { "system_message", n => { SystemMessage = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("prompt_template", PromptTemplate);
            writer.WriteStringValue("system_message", SystemMessage);
        }
    }
}
#pragma warning restore CS0618
