// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Box AI handles text documents with text representations up to 1MB in size, or a maximum of 25 files,whichever comes first. If the text file size exceeds 1MB, the first 1MB of text representation will be processed.Box AI handles image documents with a resolution of 1024 x 1024 pixels, with a maximum of 5 images or 5 pagesfor multi-page images. If the number of image or image pages exceeds 5, the first 5 images or pages willbe processed. If you set mode parameter to `single_item_qa`, the items array can have one element only.Currently Box AI does not support multi-modal requests. If both images and text are sent Box AI will onlyprocess the text.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiAsk_mode
    {
        [EnumMember(Value = "multiple_item_qa")]
        #pragma warning disable CS1591
        Multiple_item_qa,
        #pragma warning restore CS1591
        [EnumMember(Value = "single_item_qa")]
        #pragma warning disable CS1591
        Single_item_qa,
        #pragma warning restore CS1591
    }
}
