// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// AI Extract Structured Request object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiExtractStructured : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ai_agent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.AiExtractStructuredAgent? AiAgent { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.AiExtractStructuredAgent AiAgent { get; set; }
#endif
        /// <summary>The fields to be extracted from the provided items.For your request to work, you must provide either `metadata_template` or `fields`, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_fields>? Fields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_fields> Fields { get; set; }
#endif
        /// <summary>A flag to indicate whether confidence scores for every extracted field should be returned.</summary>
        public bool? IncludeConfidenceScore { get; set; }
        /// <summary>A flag to indicate whether references for every extracted field should be returned.</summary>
        public bool? IncludeReference { get; set; }
        /// <summary>The items to be processed by the LLM. Currently you can use files only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.AiItemBase>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.AiItemBase> Items { get; set; }
#endif
        /// <summary>The metadata template containing the fields to extract.For your request to work, you must provide either `metadata_template` or `fields`, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_metadata_template? MetadataTemplate { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_metadata_template MetadataTemplate { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured"/> and sets the default values.
        /// </summary>
        public AiExtractStructured()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ai_agent", n => { AiAgent = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructuredAgent>(global::Soenneker.Box.OpenApiClient.Models.AiExtractStructuredAgent.CreateFromDiscriminatorValue); } },
                { "fields", n => { Fields = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_fields>(global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_fields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "include_confidence_score", n => { IncludeConfidenceScore = n.GetBoolValue(); } },
                { "include_reference", n => { IncludeReference = n.GetBoolValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.AiItemBase>(global::Soenneker.Box.OpenApiClient.Models.AiItemBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "metadata_template", n => { MetadataTemplate = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_metadata_template>(global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_metadata_template.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructuredAgent>("ai_agent", AiAgent);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_fields>("fields", Fields);
            writer.WriteBoolValue("include_confidence_score", IncludeConfidenceScore);
            writer.WriteBoolValue("include_reference", IncludeReference);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.AiItemBase>("items", Items);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiExtractStructured_metadata_template>("metadata_template", MetadataTemplate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
