// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The type of the AI LLM endpoint params object for IBM.This parameter is **required**.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiLlmEndpointParamsIBM_type
    {
        [EnumMember(Value = "ibm_params")]
        #pragma warning disable CS1591
        Ibm_params,
        #pragma warning restore CS1591
    }
}
