// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// The AI agent to be used to generate text.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiStudioAgentTextGen : IAdditionalDataHolder, IParsable
    {
        /// <summary>The state of the AI Agent capability. Possible values are: `enabled` and `disabled`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessState { get; set; }
#nullable restore
#else
        public string AccessState { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>AI agent basic tool used to generate text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicGenTool? BasicGen { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicGenTool BasicGen { get; set; }
#endif
        /// <summary>Custom instructions for the AI agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomInstructions { get; set; }
#nullable restore
#else
        public string CustomInstructions { get; set; }
#endif
        /// <summary>The description of the AI agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Suggested questions for the AI agent. If null, suggested question will be generated. If empty, no suggested questions will be displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SuggestedQuestions { get; set; }
#nullable restore
#else
        public List<string> SuggestedQuestions { get; set; }
#endif
        /// <summary>The type of AI agent used for generating text.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen"/> and sets the default values.
        /// </summary>
        public AiStudioAgentTextGen()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_state", n => { AccessState = n.GetStringValue(); } },
                { "basic_gen", n => { BasicGen = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicGenTool>(global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicGenTool.CreateFromDiscriminatorValue); } },
                { "custom_instructions", n => { CustomInstructions = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "suggested_questions", n => { SuggestedQuestions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_state", AccessState);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicGenTool>("basic_gen", BasicGen);
            writer.WriteStringValue("custom_instructions", CustomInstructions);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("suggested_questions", SuggestedQuestions);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentTextGen_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
