// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// The AI agent to be used for metadata extraction.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiStudioAgentExtract : IAdditionalDataHolder, IParsable
    {
        /// <summary>The state of the AI Agent capability. Possible values are: `enabled` and `disabled`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessState { get; set; }
#nullable restore
#else
        public string AccessState { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>AI agent processor used to handle basic text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool? BasicImage { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool BasicImage { get; set; }
#endif
        /// <summary>AI agent processor used to handle basic text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool? BasicText { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool BasicText { get; set; }
#endif
        /// <summary>Custom instructions for the AI agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomInstructions { get; set; }
#nullable restore
#else
        public string CustomInstructions { get; set; }
#endif
        /// <summary>The description of the AI agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>AI agent processor used to to handle longer text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool? LongText { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool LongText { get; set; }
#endif
        /// <summary>The type of AI agent to be used for metadata extraction.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract"/> and sets the default values.
        /// </summary>
        public AiStudioAgentExtract()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_state", n => { AccessState = n.GetStringValue(); } },
                { "basic_image", n => { BasicImage = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool>(global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool.CreateFromDiscriminatorValue); } },
                { "basic_text", n => { BasicText = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool>(global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool.CreateFromDiscriminatorValue); } },
                { "custom_instructions", n => { CustomInstructions = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "long_text", n => { LongText = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool>(global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("access_state", AccessState);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool>("basic_image", BasicImage);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentBasicTextTool>("basic_text", BasicText);
            writer.WriteStringValue("custom_instructions", CustomInstructions);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool>("long_text", LongText);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentExtract_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
