// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// AI agent processor used to to handle longer text.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AiStudioAgentLongTextTool : global::Soenneker.Box.OpenApiClient.Models.AiAgentLongTextTool, IParsable
    {
        /// <summary>True if system message contains custom instructions placeholder, false otherwise.</summary>
        public bool? IsCustomInstructionsIncluded { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.AiStudioAgentLongTextTool();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "is_custom_instructions_included", n => { IsCustomInstructionsIncluded = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("is_custom_instructions_included", IsCustomInstructionsIncluded);
        }
    }
}
#pragma warning restore CS0618
