// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The name of this template as shown in web and mobile interfaces.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClassificationTemplate_displayName
    {
        [EnumMember(Value = "Classification")]
        #pragma warning disable CS1591
        Classification,
        #pragma warning restore CS1591
    }
}
