// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A generic error.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientError : ApiException, IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A Box-specific error code.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.ClientError_code? Code { get; set; }
        /// <summary>A free-form object that contains additional contextabout the error. The possible fields are defined ona per-endpoint basis. `message` is only one example.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.ClientError_context_info? ContextInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.ClientError_context_info ContextInfo { get; set; }
#endif
        /// <summary>A URL that links to more information about why this error occurred.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HelpUrl { get; set; }
#nullable restore
#else
        public string HelpUrl { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => MessageEscaped ?? string.Empty; }
        /// <summary>A short message describing the error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageEscaped { get; set; }
#nullable restore
#else
        public string MessageEscaped { get; set; }
#endif
        /// <summary>A unique identifier for this response, which can be usedwhen contacting Box support.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>The HTTP status of the response.</summary>
        public int? Status { get; set; }
        /// <summary>The value will always be `error`.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.ClientError_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.ClientError"/> and sets the default values.
        /// </summary>
        public ClientError()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.ClientError"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.ClientError CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.ClientError();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.ClientError_code>(); } },
                { "context_info", n => { ContextInfo = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.ClientError_context_info>(global::Soenneker.Box.OpenApiClient.Models.ClientError_context_info.CreateFromDiscriminatorValue); } },
                { "help_url", n => { HelpUrl = n.GetStringValue(); } },
                { "message", n => { MessageEscaped = n.GetStringValue(); } },
                { "request_id", n => { RequestId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.ClientError_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.ClientError_code>("code", Code);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.ClientError_context_info>("context_info", ContextInfo);
            writer.WriteStringValue("help_url", HelpUrl);
            writer.WriteStringValue("message", MessageEscaped);
            writer.WriteStringValue("request_id", RequestId);
            writer.WriteIntValue("status", Status);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.ClientError_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
