// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// The description of an event that happened within Box.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Event : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>This object provides additional information about the event if available.This can include how a user performed an event as well as additionalinformation to correlate an event to external KeySafe logs. Not all eventshave an `additional_details` object.  This object is only available in theEnterprise Events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.Event_additional_details? AdditionalDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.Event_additional_details AdditionalDetails { get; set; }
#endif
        /// <summary>When the event object was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini CreatedBy { get; set; }
#endif
        /// <summary>The ID of the event object. You can use this to detect duplicate events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventId { get; set; }
#nullable restore
#else
        public string EventId { get; set; }
#endif
        /// <summary>The event_type property</summary>
        public global::Soenneker.Box.OpenApiClient.Models.Event_event_type? EventType { get; set; }
        /// <summary>When the event object was recorded in database.</summary>
        public DateTimeOffset? RecordedAt { get; set; }
        /// <summary>The session of the user that performed the action. Not all events willpopulate this attribute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.EventSourceResource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.EventSourceResource Source { get; set; }
#endif
        /// <summary>The value will always be `event`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.Event"/> and sets the default values.
        /// </summary>
        public Event()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Event"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.Event CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.Event();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additional_details", n => { AdditionalDetails = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.Event_additional_details>(global::Soenneker.Box.OpenApiClient.Models.Event_additional_details.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "event_id", n => { EventId = n.GetStringValue(); } },
                { "event_type", n => { EventType = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.Event_event_type>(); } },
                { "recorded_at", n => { RecordedAt = n.GetDateTimeOffsetValue(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.EventSourceResource>(global::Soenneker.Box.OpenApiClient.Models.EventSourceResource.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.Event_additional_details>("additional_details", AdditionalDetails);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("created_by", CreatedBy);
            writer.WriteStringValue("event_id", EventId);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.Event_event_type>("event_type", EventType);
            writer.WriteDateTimeOffsetValue("recorded_at", RecordedAt);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.EventSourceResource>("source", Source);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
