// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A standard representation of a file version.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FileVersion : global::Soenneker.Box.OpenApiClient.Models.FileVersionMini, IParsable
    {
        /// <summary>When the file version object was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>When the file version object was last updated.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The modified_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? ModifiedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini ModifiedBy { get; set; }
#endif
        /// <summary>The name of the file version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When the file version object will be permanently deleted.</summary>
        public DateTimeOffset? PurgedAt { get; set; }
        /// <summary>When the file version was restored from the trash.</summary>
        public DateTimeOffset? RestoredAt { get; set; }
        /// <summary>The restored_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? RestoredBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini RestoredBy { get; set; }
#endif
        /// <summary>Size of the file version in bytes.</summary>
        public long? Size { get; set; }
        /// <summary>When the file version object was trashed.</summary>
        public DateTimeOffset? TrashedAt { get; set; }
        /// <summary>The trashed_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? TrashedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini TrashedBy { get; set; }
#endif
        /// <summary>The uploader_display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UploaderDisplayName { get; set; }
#nullable restore
#else
        public string UploaderDisplayName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.FileVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Box.OpenApiClient.Models.FileVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.FileVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "modified_by", n => { ModifiedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "purged_at", n => { PurgedAt = n.GetDateTimeOffsetValue(); } },
                { "restored_at", n => { RestoredAt = n.GetDateTimeOffsetValue(); } },
                { "restored_by", n => { RestoredBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "trashed_at", n => { TrashedAt = n.GetDateTimeOffsetValue(); } },
                { "trashed_by", n => { TrashedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "uploader_display_name", n => { UploaderDisplayName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("modified_by", ModifiedBy);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("purged_at", PurgedAt);
            writer.WriteDateTimeOffsetValue("restored_at", RestoredAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("restored_by", RestoredBy);
            writer.WriteLongValue("size", Size);
            writer.WriteDateTimeOffsetValue("trashed_at", TrashedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("trashed_by", TrashedBy);
            writer.WriteStringValue("uploader_display_name", UploaderDisplayName);
        }
    }
}
#pragma warning restore CS0618
