// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FileFull_shared_link_permission_options
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "can_preview")]
        #pragma warning disable CS1591
        Can_preview,
        #pragma warning restore CS1591
        [EnumMember(Value = "can_download")]
        #pragma warning disable CS1591
        Can_download,
        #pragma warning restore CS1591
        [EnumMember(Value = "can_edit")]
        #pragma warning disable CS1591
        Can_edit,
        #pragma warning restore CS1591
    }
}
