// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A standard representation of a file request, as returnedfrom any file request API endpoints by default.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FileRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date and time when the file request was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini CreatedBy { get; set; }
#endif
        /// <summary>The optional description of this file request. This isshown in the Box UI to users uploading files.This defaults to description of the file request that wascopied to create this file request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The HTTP `etag` of this file. This can be used in combination withthe `If-Match` header when updating a file request. By providing thatheader, a change will only be performed on the  file request if the `etag`on the file request still matches the `etag` provided in the `If-Match`header.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The date after which a file request will no longer accept newsubmissions.After this date, the `status` will automatically be set to`inactive`.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FolderMini? Folder { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FolderMini Folder { get; set; }
#endif
        /// <summary>The unique identifier for this file request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary>Whether a file request submitter is required to providea description of the files they are submitting.When this setting is set to true, the Box UI will showa description field on the file request form.This defaults to setting of file request that wascopied to create this file request.</summary>
        public bool? IsDescriptionRequired { get; set; }
        /// <summary>Whether a file request submitter is required to providetheir email address.When this setting is set to true, the Box UI will showan email field on the file request form.This defaults to setting of file request that wascopied to create this file request.</summary>
        public bool? IsEmailRequired { get; set; }
        /// <summary>The status of the file request. This defaultsto `active`.When the status is set to `inactive`, the file requestwill no longer accept new submissions, and any visitorto the file request URL will receive a `HTTP 404` statuscode.This defaults to status of file request that wascopied to create this file request.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.FileRequest_status? Status { get; set; }
        /// <summary>The title of file request. This is shownin the Box UI to users uploading files.This defaults to title of the file request that wascopied to create this file request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The value will always be `file_request`.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.FileRequest_type? Type { get; private set; }
        /// <summary>The date and time when the file request was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? UpdatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini UpdatedBy { get; set; }
#endif
        /// <summary>The generated URL for this file request. This URL can be sharedwith users to let them upload files to the associated folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; private set; }
#nullable restore
#else
        public string Url { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.FileRequest"/> and sets the default values.
        /// </summary>
        public FileRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.FileRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.FileRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.FileRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "folder", n => { Folder = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderMini>(global::Soenneker.Box.OpenApiClient.Models.FolderMini.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_description_required", n => { IsDescriptionRequired = n.GetBoolValue(); } },
                { "is_email_required", n => { IsEmailRequired = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.FileRequest_status>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.FileRequest_type>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("created_by", CreatedBy);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("etag", Etag);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderMini>("folder", Folder);
            writer.WriteBoolValue("is_description_required", IsDescriptionRequired);
            writer.WriteBoolValue("is_email_required", IsEmailRequired);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.FileRequest_status>("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("updated_by", UpdatedBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
