// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FolderFull_allowed_invitee_roles
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "editor")]
        #pragma warning disable CS1591
        Editor,
        #pragma warning restore CS1591
        [EnumMember(Value = "viewer")]
        #pragma warning disable CS1591
        Viewer,
        #pragma warning restore CS1591
        [EnumMember(Value = "previewer")]
        #pragma warning disable CS1591
        Previewer,
        #pragma warning restore CS1591
        [EnumMember(Value = "uploader")]
        #pragma warning disable CS1591
        Uploader,
        #pragma warning restore CS1591
        [EnumMember(Value = "previewer uploader")]
        #pragma warning disable CS1591
        PreviewerUploader,
        #pragma warning restore CS1591
        [EnumMember(Value = "viewer uploader")]
        #pragma warning disable CS1591
        ViewerUploader,
        #pragma warning restore CS1591
        [EnumMember(Value = "co-owner")]
        #pragma warning disable CS1591
        CoOwner,
        #pragma warning restore CS1591
    }
}
