// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// Defines if this link allows a user to preview, edit, and download an item.These permissions refer to the shared link only anddo not supersede permissions applied to the item itself.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Folder_shared_link_permissions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defines if the shared link allows for the item to be downloaded. Forshared links on folders, this also applies to any items in the folder.This value can be set to `true` when the effective access level isset to `open` or `company`, not `collaborators`.</summary>
        public bool? CanDownload { get; set; }
        /// <summary>Defines if the shared link allows for the item to be edited.This value can only be `true` if `can_download` is also `true` and ifthe item has a type of `file`.</summary>
        public bool? CanEdit { get; set; }
        /// <summary>Defines if the shared link allows for the item to be previewed.This value is always `true`. For shared links on folders this alsoapplies to any items in the folder.</summary>
        public bool? CanPreview { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.Folder_shared_link_permissions"/> and sets the default values.
        /// </summary>
        public Folder_shared_link_permissions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Folder_shared_link_permissions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.Folder_shared_link_permissions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.Folder_shared_link_permissions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "can_download", n => { CanDownload = n.GetBoolValue(); } },
                { "can_edit", n => { CanEdit = n.GetBoolValue(); } },
                { "can_preview", n => { CanPreview = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("can_download", CanDownload);
            writer.WriteBoolValue("can_edit", CanEdit);
            writer.WriteBoolValue("can_preview", CanPreview);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
