// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A full representation of a folder, as can be returned from anyfolder API endpoints by default.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FolderFull : global::Soenneker.Box.OpenApiClient.Models.Folder, IParsable
    {
        /// <summary>A list of the types of roles that user can be invited atwhen sharing this folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_invitee_roles?>? AllowedInviteeRoles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_invitee_roles?> AllowedInviteeRoles { get; set; }
#endif
        /// <summary>A list of access levels that are availablefor this folder.For some folders, like the root folder, this will alwaysbe an empty list as sharing is not allowed at that level.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_shared_link_access_levels?>? AllowedSharedLinkAccessLevels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_shared_link_access_levels?> AllowedSharedLinkAccessLevels { get; set; }
#endif
        /// <summary>The can_non_owners_invite property</summary>
        public bool? CanNonOwnersInvite { get; set; }
        /// <summary>Specifies if collaborators who are not ownersof this folder are restricted from viewing othercollaborations on this folder.It also restricts non-owners from inviting newcollaborators.</summary>
        public bool? CanNonOwnersViewCollaborators { get; set; }
        /// <summary>The classification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FolderFull_classification? Classification { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FolderFull_classification Classification { get; set; }
#endif
        /// <summary>Specifies if this folder has any other collaborators.</summary>
        public bool? HasCollaborations { get; set; }
        /// <summary>Specifies if the folder can be accessedwith the direct shared link or a shared linkto a parent folder.</summary>
        public bool? IsAccessibleViaSharedLink { get; set; }
        /// <summary>This field will return true if the folder or any ancestor of thefolder is associated with at least one app item. Note that this willreturn true even if the context user does not have access to theapp item(s) associated with the folder.</summary>
        public bool? IsAssociatedWithAppItem { get; set; }
        /// <summary>The is_collaboration_restricted_to_enterprise property</summary>
        public bool? IsCollaborationRestrictedToEnterprise { get; set; }
        /// <summary>Specifies if this folder is owned by a user outside of theauthenticated enterprise.</summary>
        public bool? IsExternallyOwned { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Metadata { get; set; }
#nullable restore
#else
        public UntypedNode Metadata { get; set; }
#endif
        /// <summary>The permissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Permissions { get; set; }
#nullable restore
#else
        public UntypedNode Permissions { get; set; }
#endif
        /// <summary>The sync_state property</summary>
        public global::Soenneker.Box.OpenApiClient.Models.FolderFull_sync_state? SyncState { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The watermark_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FolderFull_watermark_info? WatermarkInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FolderFull_watermark_info WatermarkInfo { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.FolderFull"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Box.OpenApiClient.Models.FolderFull CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.FolderFull();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "allowed_invitee_roles", n => { AllowedInviteeRoles = n.GetCollectionOfEnumValues<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_invitee_roles>()?.AsList(); } },
                { "allowed_shared_link_access_levels", n => { AllowedSharedLinkAccessLevels = n.GetCollectionOfEnumValues<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_shared_link_access_levels>()?.AsList(); } },
                { "can_non_owners_invite", n => { CanNonOwnersInvite = n.GetBoolValue(); } },
                { "can_non_owners_view_collaborators", n => { CanNonOwnersViewCollaborators = n.GetBoolValue(); } },
                { "classification", n => { Classification = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderFull_classification>(global::Soenneker.Box.OpenApiClient.Models.FolderFull_classification.CreateFromDiscriminatorValue); } },
                { "has_collaborations", n => { HasCollaborations = n.GetBoolValue(); } },
                { "is_accessible_via_shared_link", n => { IsAccessibleViaSharedLink = n.GetBoolValue(); } },
                { "is_associated_with_app_item", n => { IsAssociatedWithAppItem = n.GetBoolValue(); } },
                { "is_collaboration_restricted_to_enterprise", n => { IsCollaborationRestrictedToEnterprise = n.GetBoolValue(); } },
                { "is_externally_owned", n => { IsExternallyOwned = n.GetBoolValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "permissions", n => { Permissions = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "sync_state", n => { SyncState = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.FolderFull_sync_state>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "watermark_info", n => { WatermarkInfo = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderFull_watermark_info>(global::Soenneker.Box.OpenApiClient.Models.FolderFull_watermark_info.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_invitee_roles>("allowed_invitee_roles", AllowedInviteeRoles);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Box.OpenApiClient.Models.FolderFull_allowed_shared_link_access_levels>("allowed_shared_link_access_levels", AllowedSharedLinkAccessLevels);
            writer.WriteBoolValue("can_non_owners_invite", CanNonOwnersInvite);
            writer.WriteBoolValue("can_non_owners_view_collaborators", CanNonOwnersViewCollaborators);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderFull_classification>("classification", Classification);
            writer.WriteBoolValue("has_collaborations", HasCollaborations);
            writer.WriteBoolValue("is_accessible_via_shared_link", IsAccessibleViaSharedLink);
            writer.WriteBoolValue("is_associated_with_app_item", IsAssociatedWithAppItem);
            writer.WriteBoolValue("is_collaboration_restricted_to_enterprise", IsCollaborationRestrictedToEnterprise);
            writer.WriteBoolValue("is_externally_owned", IsExternallyOwned);
            writer.WriteObjectValue<UntypedNode>("metadata", Metadata);
            writer.WriteObjectValue<UntypedNode>("permissions", Permissions);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.FolderFull_sync_state>("sync_state", SyncState);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderFull_watermark_info>("watermark_info", WatermarkInfo);
        }
    }
}
#pragma warning restore CS0618
