// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Specifies who can view the members of the group(Get Memberships for Group).* `admins_only` - the enterprise admin, co-admins, group&apos;s  group admin.* `admins_and_members` - all admins and group members.* `all_managed_users` - all managed users in the  enterprise.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GroupFull_member_viewability_level
    {
        [EnumMember(Value = "admins_only")]
        #pragma warning disable CS1591
        Admins_only,
        #pragma warning restore CS1591
        [EnumMember(Value = "admins_and_members")]
        #pragma warning disable CS1591
        Admins_and_members,
        #pragma warning restore CS1591
        [EnumMember(Value = "all_managed_users")]
        #pragma warning disable CS1591
        All_managed_users,
        #pragma warning restore CS1591
    }
}
