// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The value will always be `enterprise`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Invite_invited_to_type
    {
        [EnumMember(Value = "enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
    }
}
