// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The value will always be `legal_hold_policy_assignment`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LegalHoldPolicyAssignmentBase_type
    {
        [EnumMember(Value = "legal_hold_policy_assignment")]
        #pragma warning disable CS1591
        Legal_hold_policy_assignment,
        #pragma warning restore CS1591
    }
}
