// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The direction to order by, either ascending or descending.The `ordering` direction must be the same for each item in thearray.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MetadataQuery_order_by_direction
    {
        [EnumMember(Value = "ASC")]
        #pragma warning disable CS1591
        ASC,
        #pragma warning restore CS1591
        [EnumMember(Value = "DESC")]
        #pragma warning disable CS1591
        DESC,
        #pragma warning restore CS1591
    }
}
