// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// Create a search using SQL-like syntax to return items that match specificmetadata.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MetadataQuery : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the folder that you are restricting the query to. Avalue of zero will return results from all folders you have accessto. A non-zero value will only return results found in the foldercorresponding to the ID or in any of its subfolders.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AncestorFolderId { get; set; }
#nullable restore
#else
        public string AncestorFolderId { get; set; }
#endif
        /// <summary>By default, this endpoint returns only the most basic info about the items forwhich the query matches. This attribute can be used to specify a list ofadditional attributes to return for any item, including its metadata.This attribute takes a list of item fields, metadata template identifiers,or metadata template field identifiers.For example:* `created_by` will add the details of the user who created the item tothe response.* `metadata.&lt;scope&gt;.&lt;templateKey&gt;` will return the mini-representationof the metadata instance identified by the `scope` and `templateKey`.* `metadata.&lt;scope&gt;.&lt;templateKey&gt;.&lt;field&gt;` will return all the mini-representationof the metadata instance identified by the `scope` and `templateKey` plusthe field specified by the `field` name. Multiple fields for the same`scope` and `templateKey` can be defined.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Fields { get; set; }
#nullable restore
#else
        public List<string> Fields { get; set; }
#endif
        /// <summary>Specifies the template used in the query. Must be in the form`scope.templateKey`. Not all templates can be used in this field,most notably the built-in, Box-provided classification templatescan not be used in a query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>A value between 0 and 100 that indicates the maximum number of resultsto return for a single request. This only specifies a maximumboundary and will not guarantee the minimum number of resultsreturned.</summary>
        public int? Limit { get; set; }
        /// <summary>Marker to use for requesting the next page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Marker { get; set; }
#nullable restore
#else
        public string Marker { get; set; }
#endif
        /// <summary>A list of template fields and directions to sort the metadata queryresults by.The ordering `direction` must be the same for each item in the array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_order_by>? OrderBy { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_order_by> OrderBy { get; set; }
#endif
        /// <summary>The query to perform. A query is a logical expression that is very similarto a SQL `SELECT` statement. Values in the search query can be turned intoparameters specified in the `query_param` arguments list to prevent havingto manually insert search values into the query string.For example, a value of `:amount` would represent the `amount` value in`query_params` object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Set of arguments corresponding to the parameters specified in the`query`. The type of each parameter used in the `query_params` must matchthe type of the corresponding metadata template field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_query_params? QueryParams { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_query_params QueryParams { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.MetadataQuery"/> and sets the default values.
        /// </summary>
        public MetadataQuery()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.MetadataQuery"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.MetadataQuery CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.MetadataQuery();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ancestor_folder_id", n => { AncestorFolderId = n.GetStringValue(); } },
                { "fields", n => { Fields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "marker", n => { Marker = n.GetStringValue(); } },
                { "order_by", n => { OrderBy = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_order_by>(global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_order_by.CreateFromDiscriminatorValue)?.AsList(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "query_params", n => { QueryParams = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_query_params>(global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_query_params.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("ancestor_folder_id", AncestorFolderId);
            writer.WriteCollectionOfPrimitiveValues<string>("fields", Fields);
            writer.WriteStringValue("from", From);
            writer.WriteIntValue("limit", Limit);
            writer.WriteStringValue("marker", Marker);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_order_by>("order_by", OrderBy);
            writer.WriteStringValue("query", Query);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.MetadataQuery_query_params>("query_params", QueryParams);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
