// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Specifies the retention type:* `modifiable`: You can modify the retention policy. For example, you can add or remove folders, shorten or lengthen the policy duration, or delete the assignment. Use this type if your retention policy is not related to any regulatory purposes.* `non-modifiable`: You can modify the retention policy only in a limited way: add a folder, lengthen the duration, retire the policy, change the disposition action or notification settings. You cannot perform other actions, such as deleting the assignment or shortening the policy duration. Use this type to ensure compliance with regulatory retention policies.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RetentionPolicy_retention_type
    {
        [EnumMember(Value = "modifiable")]
        #pragma warning disable CS1591
        Modifiable,
        #pragma warning restore CS1591
        [EnumMember(Value = "non_modifiable")]
        #pragma warning disable CS1591
        Non_modifiable,
        #pragma warning restore CS1591
    }
}
