// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The variable type usedby the object.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RoleVariable_variable_type
    {
        [EnumMember(Value = "collaborator_role")]
        #pragma warning disable CS1591
        Collaborator_role,
        #pragma warning restore CS1591
    }
}
