// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A list of files, folders and web links that matched the search query.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchResults : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The search results for the query provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.SearchResultItem>? Entries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.SearchResultItem> Entries { get; set; }
#endif
        /// <summary>The limit that was used for this search. This will be the same as the`limit` query parameter unless that value exceeded the maximum valueallowed.</summary>
        public long? Limit { get; set; }
        /// <summary>The 0-based offset of the first entry in this set. This will be the sameas the `offset` query parameter used.</summary>
        public long? Offset { get; set; }
        /// <summary>One greater than the offset of the last entry in the search results.The total number of entries in the collection may be less than`total_count`.</summary>
        public long? TotalCount { get; set; }
        /// <summary>Specifies the response as search result items without shared links.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.SearchResults_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.SearchResults"/> and sets the default values.
        /// </summary>
        public SearchResults()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.SearchResults"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.SearchResults CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.SearchResults();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.SearchResultItem>(global::Soenneker.Box.OpenApiClient.Models.SearchResultItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "limit", n => { Limit = n.GetLongValue(); } },
                { "offset", n => { Offset = n.GetLongValue(); } },
                { "total_count", n => { TotalCount = n.GetLongValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.SearchResults_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.SearchResultItem>("entries", Entries);
            writer.WriteLongValue("limit", Limit);
            writer.WriteLongValue("offset", Offset);
            writer.WriteLongValue("total_count", TotalCount);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.SearchResults_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
