// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A standard representation of asegment restriction of a shield information barrierobject.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShieldInformationBarrierSegmentRestriction : global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierSegmentRestrictionMini, IParsable
    {
        /// <summary>ISO date time string when thisshield information barrierSegment Restriction object was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserBase? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserBase CreatedBy { get; set; }
#endif
        /// <summary>A base representation of ashield information barrier object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierBase? ShieldInformationBarrier { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierBase ShieldInformationBarrier { get; set; }
#endif
        /// <summary>ISO date time string when thisshield information barrier segmentRestriction was updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The updated_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserBase? UpdatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserBase UpdatedBy { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierSegmentRestriction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierSegmentRestriction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierSegmentRestriction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserBase>(global::Soenneker.Box.OpenApiClient.Models.UserBase.CreateFromDiscriminatorValue); } },
                { "shield_information_barrier", n => { ShieldInformationBarrier = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierBase>(global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierBase.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserBase>(global::Soenneker.Box.OpenApiClient.Models.UserBase.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserBase>("created_by", CreatedBy);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.ShieldInformationBarrierBase>("shield_information_barrier", ShieldInformationBarrier);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserBase>("updated_by", UpdatedBy);
        }
    }
}
#pragma warning restore CS0618
