// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// Specifies the custom validation rules for a text field input by the signer.If set, this validation is mandatory.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignRequestSignerInputCustomValidation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Error message shown if input fails custom regular expression validation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomErrorMessage { get; set; }
#nullable restore
#else
        public string CustomErrorMessage { get; set; }
#endif
        /// <summary>Regular expression used for validation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomRegex { get; set; }
#nullable restore
#else
        public string CustomRegex { get; set; }
#endif
        /// <summary>Defines the validation format for the text input as custom.A custom regular expression is used for validation.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation_validation_type? ValidationType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation"/> and sets the default values.
        /// </summary>
        public SignRequestSignerInputCustomValidation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_error_message", n => { CustomErrorMessage = n.GetStringValue(); } },
                { "custom_regex", n => { CustomRegex = n.GetStringValue(); } },
                { "validation_type", n => { ValidationType = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation_validation_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("custom_error_message", CustomErrorMessage);
            writer.WriteStringValue("custom_regex", CustomRegex);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.SignRequestSignerInputCustomValidation_validation_type>("validation_type", ValidationType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
