// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// List of files that will be signed, which are copies of the originalsource files. A new version of these files are created as signers signand can be downloaded at any point in the signing process.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignRequest_sign_files : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The files property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.FileMini>? Files { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.FileMini> Files { get; set; }
#endif
        /// <summary>Indicates whether the `sign_files` documents are processingand the PDFs may be out of date. A change to any documentrequires processing on all `sign_files`. Werecommended waiting until processing is finished(and this value is true) before downloading the PDFs.</summary>
        public bool? IsReadyForDownload { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.SignRequest_sign_files"/> and sets the default values.
        /// </summary>
        public SignRequest_sign_files()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.SignRequest_sign_files"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.SignRequest_sign_files CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.SignRequest_sign_files();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "files", n => { Files = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.FileMini>(global::Soenneker.Box.OpenApiClient.Models.FileMini.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_ready_for_download", n => { IsReadyForDownload = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.FileMini>("files", Files);
            writer.WriteBoolValue("is_ready_for_download", IsReadyForDownload);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
