// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Validates that the text input is a Social Security Number (SSN).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SignRequestSignerInputSSNValidation_validation_type
    {
        [EnumMember(Value = "ssn")]
        #pragma warning disable CS1591
        Ssn,
        #pragma warning restore CS1591
    }
}
