// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// The metadata assigned to a using for Box skills.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SkillCardsMetadata : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the user can edit this metadata.</summary>
        public bool? CanEdit { get; set; }
        /// <summary>A list of Box Skill cards that have been applied to this file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.SkillCard>? Cards { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.SkillCard> Cards { get; set; }
#endif
        /// <summary>A UUID to identify the metadata object.</summary>
        public Guid? Id { get; set; }
        /// <summary>An ID for the parent folder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Parent { get; set; }
#nullable restore
#else
        public string Parent { get; set; }
#endif
        /// <summary>An ID for the scope in which this templatehas been applied.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scope { get; set; }
#nullable restore
#else
        public string Scope { get; set; }
#endif
        /// <summary>The name of the template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Template { get; set; }
#nullable restore
#else
        public string Template { get; set; }
#endif
        /// <summary>A unique identifier for the &quot;type&quot; of this instance. This is an internalsystem property and should not be used by a client application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The last-known version of the template of the object. This is an internalsystem property and should not be used by a client application.</summary>
        public int? TypeVersion { get; set; }
        /// <summary>The version of the metadata object. Starts at 0 and increases every timea user-defined property is modified.</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.SkillCardsMetadata"/> and sets the default values.
        /// </summary>
        public SkillCardsMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.SkillCardsMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.SkillCardsMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.SkillCardsMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "$canEdit", n => { CanEdit = n.GetBoolValue(); } },
                { "cards", n => { Cards = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.SkillCard>(global::Soenneker.Box.OpenApiClient.Models.SkillCard.CreateFromDiscriminatorValue)?.AsList(); } },
                { "$id", n => { Id = n.GetGuidValue(); } },
                { "$parent", n => { Parent = n.GetStringValue(); } },
                { "$scope", n => { Scope = n.GetStringValue(); } },
                { "$template", n => { Template = n.GetStringValue(); } },
                { "$type", n => { Type = n.GetStringValue(); } },
                { "$typeVersion", n => { TypeVersion = n.GetIntValue(); } },
                { "$version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("$canEdit", CanEdit);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.SkillCard>("cards", Cards);
            writer.WriteGuidValue("$id", Id);
            writer.WriteStringValue("$parent", Parent);
            writer.WriteStringValue("$scope", Scope);
            writer.WriteStringValue("$template", Template);
            writer.WriteStringValue("$type", Type);
            writer.WriteIntValue("$typeVersion", TypeVersion);
            writer.WriteIntValue("$version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
