// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A task allows for file-centric workflows within Box. Users cancreate tasks on files and assign them to other users for them to complete thetasks.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>The type of task the task assignee will be prompted toperform.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.Task_action? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defines which assignees need to complete this task before the taskis considered completed.* `all_assignees` requires all assignees to review orapprove the task in order for it to be considered completed.* `any_assignee` accepts any one assignee to review orapprove the task in order for it to be considered completed.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.Task_completion_rule? CompletionRule { get; set; }
        /// <summary>When the task object was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini CreatedBy { get; set; }
#endif
        /// <summary>When the task is due.</summary>
        public DateTimeOffset? DueAt { get; set; }
        /// <summary>The unique identifier for this task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the task has been completed.</summary>
        public bool? IsCompleted { get; set; }
        /// <summary>The item property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FileMini? Item { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FileMini Item { get; set; }
#endif
        /// <summary>A message that will be included with the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The task_assignment_collection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.TaskAssignments? TaskAssignmentCollection { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.TaskAssignments TaskAssignmentCollection { get; set; }
#endif
        /// <summary>The value will always be `task`.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.Task_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.TaskObject"/> and sets the default values.
        /// </summary>
        public TaskObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.TaskObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.TaskObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.TaskObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.Task_action>(); } },
                { "completion_rule", n => { CompletionRule = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.Task_completion_rule>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "due_at", n => { DueAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_completed", n => { IsCompleted = n.GetBoolValue(); } },
                { "item", n => { Item = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FileMini>(global::Soenneker.Box.OpenApiClient.Models.FileMini.CreateFromDiscriminatorValue); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "task_assignment_collection", n => { TaskAssignmentCollection = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.TaskAssignments>(global::Soenneker.Box.OpenApiClient.Models.TaskAssignments.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.Task_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.Task_action>("action", Action);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.Task_completion_rule>("completion_rule", CompletionRule);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("created_by", CreatedBy);
            writer.WriteDateTimeOffsetValue("due_at", DueAt);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_completed", IsCompleted);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FileMini>("item", Item);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.TaskAssignments>("task_assignment_collection", TaskAssignmentCollection);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.Task_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
