// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Content type of input.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TemplateSignerInput_content_type
    {
        [EnumMember(Value = "signature")]
        #pragma warning disable CS1591
        Signature,
        #pragma warning restore CS1591
        [EnumMember(Value = "initial")]
        #pragma warning disable CS1591
        Initial,
        #pragma warning restore CS1591
        [EnumMember(Value = "stamp")]
        #pragma warning disable CS1591
        Stamp,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "checkbox")]
        #pragma warning disable CS1591
        Checkbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "full_name")]
        #pragma warning disable CS1591
        Full_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_name")]
        #pragma warning disable CS1591
        First_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_name")]
        #pragma warning disable CS1591
        Last_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "company")]
        #pragma warning disable CS1591
        Company,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachment")]
        #pragma warning disable CS1591
        Attachment,
        #pragma warning restore CS1591
        [EnumMember(Value = "radio")]
        #pragma warning disable CS1591
        Radio,
        #pragma warning restore CS1591
        [EnumMember(Value = "dropdown")]
        #pragma warning disable CS1591
        Dropdown,
        #pragma warning restore CS1591
    }
}
