// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Whether these terms are enabled or not.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TermsOfService_status
    {
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
    }
}
