// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>Whether to apply these terms to managed users or external users.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TermsOfService_tos_type
    {
        [EnumMember(Value = "managed")]
        #pragma warning disable CS1591
        Managed,
        #pragma warning restore CS1591
        [EnumMember(Value = "external")]
        #pragma warning disable CS1591
        External,
        #pragma warning restore CS1591
    }
}
