// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// Represents a trashed file.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrashFile : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date and time at which this file was originallycreated, which might be before it was uploaded to Box.</summary>
        public DateTimeOffset? ContentCreatedAt { get; set; }
        /// <summary>The date and time at which this file was last updated,which might be before it was uploaded to Box.</summary>
        public DateTimeOffset? ContentModifiedAt { get; set; }
        /// <summary>The date and time when the file was created on Box.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini CreatedBy { get; set; }
#endif
        /// <summary>The optional description of this file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The HTTP `etag` of this file. This can be used within some APIendpoints in the `If-Match` and `If-None-Match` headers to onlyperform changes on the file if (no) changes have happened.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The file_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FileVersionMini? FileVersion { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FileVersionMini FileVersion { get; set; }
#endif
        /// <summary>The unique identifier that represent a file.The ID for any file can be determinedby visiting a file in the web applicationand copying the ID from the URL. For example,for the URL `https://*.app.box.com/files/123`the `file_id` is `123`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Defines if this item has been deleted or not.* `active` when the item has is not in the trash* `trashed` when the item has been moved to the trash but not deleted* `deleted` when the item has been permanently deleted.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.TrashFile_item_status? ItemStatus { get; set; }
        /// <summary>The date and time when the file was last updated on Box.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The modified_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? ModifiedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini ModifiedBy { get; set; }
#endif
        /// <summary>The name of the file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The owned_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? OwnedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini OwnedBy { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FolderMini? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FolderMini Parent { get; set; }
#endif
        /// <summary>The path_collection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.TrashFile_path_collection? PathCollection { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.TrashFile_path_collection PathCollection { get; set; }
#endif
        /// <summary>The time at which this file is expected to be purgedfrom the trash.</summary>
        public DateTimeOffset? PurgedAt { get; set; }
        /// <summary>The sequence_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>The SHA1 hash of the file. This can be used to compare the contentsof a file on Box with a local file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sha1 { get; set; }
#nullable restore
#else
        public string Sha1 { get; set; }
#endif
        /// <summary>The shared link for this file. This willbe `null` if a file has been trashed, since the link will no longerbe active.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SharedLink { get; set; }
#nullable restore
#else
        public string SharedLink { get; set; }
#endif
        /// <summary>The file size in bytes. Be careful parsing this integer as it canget very large and cause an integer overflow.</summary>
        public int? Size { get; set; }
        /// <summary>The time at which this file was put in the trash.</summary>
        public DateTimeOffset? TrashedAt { get; set; }
        /// <summary>The value will always be `file`.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.TrashFile_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.TrashFile"/> and sets the default values.
        /// </summary>
        public TrashFile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.TrashFile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.TrashFile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.TrashFile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content_created_at", n => { ContentCreatedAt = n.GetDateTimeOffsetValue(); } },
                { "content_modified_at", n => { ContentModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "file_version", n => { FileVersion = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FileVersionMini>(global::Soenneker.Box.OpenApiClient.Models.FileVersionMini.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "item_status", n => { ItemStatus = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashFile_item_status>(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "modified_by", n => { ModifiedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owned_by", n => { OwnedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderMini>(global::Soenneker.Box.OpenApiClient.Models.FolderMini.CreateFromDiscriminatorValue); } },
                { "path_collection", n => { PathCollection = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.TrashFile_path_collection>(global::Soenneker.Box.OpenApiClient.Models.TrashFile_path_collection.CreateFromDiscriminatorValue); } },
                { "purged_at", n => { PurgedAt = n.GetDateTimeOffsetValue(); } },
                { "sequence_id", n => { SequenceId = n.GetStringValue(); } },
                { "sha1", n => { Sha1 = n.GetStringValue(); } },
                { "shared_link", n => { SharedLink = n.GetStringValue(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "trashed_at", n => { TrashedAt = n.GetDateTimeOffsetValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashFile_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("content_created_at", ContentCreatedAt);
            writer.WriteDateTimeOffsetValue("content_modified_at", ContentModifiedAt);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("created_by", CreatedBy);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("etag", Etag);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FileVersionMini>("file_version", FileVersion);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashFile_item_status>("item_status", ItemStatus);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("modified_by", ModifiedBy);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("owned_by", OwnedBy);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderMini>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.TrashFile_path_collection>("path_collection", PathCollection);
            writer.WriteDateTimeOffsetValue("purged_at", PurgedAt);
            writer.WriteStringValue("sequence_id", SequenceId);
            writer.WriteStringValue("sha1", Sha1);
            writer.WriteStringValue("shared_link", SharedLink);
            writer.WriteIntValue("size", Size);
            writer.WriteDateTimeOffsetValue("trashed_at", TrashedAt);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashFile_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
