// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// Represents a trashed web link.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrashWebLink : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When this file was created on Box’s servers.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The created_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? CreatedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini CreatedBy { get; set; }
#endif
        /// <summary>The description accompanying the web link. This isvisible within the Box web application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The entity tag of this web link. Used with `If-Match`headers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Etag { get; set; }
#nullable restore
#else
        public string Etag { get; set; }
#endif
        /// <summary>The unique identifier for this web link.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this item is deleted or not. Values include `active`,`trashed` if the file has been moved to the trash, and `deleted` ifthe file has been permanently deleted.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_item_status? ItemStatus { get; set; }
        /// <summary>When this file was last updated on the Boxservers.</summary>
        public DateTimeOffset? ModifiedAt { get; set; }
        /// <summary>The modified_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? ModifiedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini ModifiedBy { get; set; }
#endif
        /// <summary>The name of the web link.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The owned_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserMini? OwnedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserMini OwnedBy { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.FolderMini? Parent { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.FolderMini Parent { get; set; }
#endif
        /// <summary>The path_collection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_path_collection? PathCollection { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_path_collection PathCollection { get; set; }
#endif
        /// <summary>When this file will be permanently deleted.</summary>
        public DateTimeOffset? PurgedAt { get; set; }
        /// <summary>The sequence_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceId { get; set; }
#nullable restore
#else
        public string SequenceId { get; set; }
#endif
        /// <summary>The shared link for this bookmark. This willbe `null` if a bookmark has been trashed, since the link will no longerbe active.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SharedLink { get; set; }
#nullable restore
#else
        public string SharedLink { get; set; }
#endif
        /// <summary>When this file was last moved to the trash.</summary>
        public DateTimeOffset? TrashedAt { get; set; }
        /// <summary>The value will always be `web_link`.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_type? Type { get; set; }
        /// <summary>The URL this web link points to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.TrashWebLink"/> and sets the default values.
        /// </summary>
        public TrashWebLink()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.TrashWebLink"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.TrashWebLink CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.TrashWebLink();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "etag", n => { Etag = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "item_status", n => { ItemStatus = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_item_status>(); } },
                { "modified_at", n => { ModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "modified_by", n => { ModifiedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owned_by", n => { OwnedBy = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>(global::Soenneker.Box.OpenApiClient.Models.UserMini.CreateFromDiscriminatorValue); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderMini>(global::Soenneker.Box.OpenApiClient.Models.FolderMini.CreateFromDiscriminatorValue); } },
                { "path_collection", n => { PathCollection = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_path_collection>(global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_path_collection.CreateFromDiscriminatorValue); } },
                { "purged_at", n => { PurgedAt = n.GetDateTimeOffsetValue(); } },
                { "sequence_id", n => { SequenceId = n.GetStringValue(); } },
                { "shared_link", n => { SharedLink = n.GetStringValue(); } },
                { "trashed_at", n => { TrashedAt = n.GetDateTimeOffsetValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_type>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("created_by", CreatedBy);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("etag", Etag);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_item_status>("item_status", ItemStatus);
            writer.WriteDateTimeOffsetValue("modified_at", ModifiedAt);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("modified_by", ModifiedBy);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserMini>("owned_by", OwnedBy);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.FolderMini>("parent", Parent);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_path_collection>("path_collection", PathCollection);
            writer.WriteDateTimeOffsetValue("purged_at", PurgedAt);
            writer.WriteStringValue("sequence_id", SequenceId);
            writer.WriteStringValue("shared_link", SharedLink);
            writer.WriteDateTimeOffsetValue("trashed_at", TrashedAt);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.TrashWebLink_type>("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
