// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The value will always be `upload_session`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UploadSession_type
    {
        [EnumMember(Value = "upload_session")]
        #pragma warning disable CS1591
        Upload_session,
        #pragma warning restore CS1591
    }
}
