// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// Response from planning an upload session.Contains information about which parts alreadyexist (hits) and which need to be uploaded (misses).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UploadSessionPlanResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Parts that already exist on the server anddo not need to be uploaded again.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlanHit>? Hits { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlanHit> Hits { get; set; }
#endif
        /// <summary>Parts that do not exist on the server andneed to be uploaded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlan>? Misses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlan> Misses { get; set; }
#endif
        /// <summary>The unique identifier for this upload session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UploadSessionId { get; set; }
#nullable restore
#else
        public string UploadSessionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Models.UploadSessionPlanResponse"/> and sets the default values.
        /// </summary>
        public UploadSessionPlanResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.UploadSessionPlanResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Box.OpenApiClient.Models.UploadSessionPlanResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.UploadSessionPlanResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "hits", n => { Hits = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlanHit>(global::Soenneker.Box.OpenApiClient.Models.UploadPartPlanHit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "misses", n => { Misses = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlan>(global::Soenneker.Box.OpenApiClient.Models.UploadPartPlan.CreateFromDiscriminatorValue)?.AsList(); } },
                { "upload_session_id", n => { UploadSessionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlanHit>("hits", Hits);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.UploadPartPlan>("misses", Misses);
            writer.WriteStringValue("upload_session_id", UploadSessionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
