// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>
    /// A full representation of a user, as can be returned from anyuser API endpoint.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserFull : global::Soenneker.Box.OpenApiClient.Models.User, IParsable
    {
        /// <summary>Whether the user can see other enterprise users in their contact list.</summary>
        public bool? CanSeeManagedUsers { get; set; }
        /// <summary>The enterprise property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Box.OpenApiClient.Models.UserFull_enterprise? Enterprise { get; set; }
#nullable restore
#else
        public global::Soenneker.Box.OpenApiClient.Models.UserFull_enterprise Enterprise { get; set; }
#endif
        /// <summary>An external identifier for an app user, which can be used to look upthe user. This can be used to tie user IDs from external identityproviders to Box users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalAppUserId { get; set; }
#nullable restore
#else
        public string ExternalAppUserId { get; set; }
#endif
        /// <summary>The root (protocol, subdomain, domain) of any links that need to begenerated for the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hostname { get; set; }
#nullable restore
#else
        public string Hostname { get; set; }
#endif
        /// <summary>Whether to exempt the user from Enterprise device limits.</summary>
        public bool? IsExemptFromDeviceLimits { get; set; }
        /// <summary>Whether the user must use two-factor authentication.</summary>
        public bool? IsExemptFromLoginVerification { get; set; }
        /// <summary>Whether the user is allowed to collaborate with users outside theirenterprise.</summary>
        public bool? IsExternalCollabRestricted { get; set; }
        /// <summary>Whether the user is an App User.</summary>
        public bool? IsPlatformAccessOnly { get; set; }
        /// <summary>Whether the user can use Box Sync.</summary>
        public bool? IsSyncEnabled { get; set; }
        /// <summary>Tags for all files and folders owned by the user. Values returnedwill only contain tags that were set by the requester.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MyTags { get; set; }
#nullable restore
#else
        public List<string> MyTags { get; set; }
#endif
        /// <summary>The user’s enterprise role.</summary>
        public global::Soenneker.Box.OpenApiClient.Models.UserFull_role? Role { get; set; }
        /// <summary>Tracking codes allow an admin to generate reports from theadmin console and assign an attribute to a specific groupof users. This setting must be enabled for an enterprisebefore it can be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Box.OpenApiClient.Models.TrackingCode>? TrackingCodes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Box.OpenApiClient.Models.TrackingCode> TrackingCodes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.UserFull"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Box.OpenApiClient.Models.UserFull CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Box.OpenApiClient.Models.UserFull();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "can_see_managed_users", n => { CanSeeManagedUsers = n.GetBoolValue(); } },
                { "enterprise", n => { Enterprise = n.GetObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserFull_enterprise>(global::Soenneker.Box.OpenApiClient.Models.UserFull_enterprise.CreateFromDiscriminatorValue); } },
                { "external_app_user_id", n => { ExternalAppUserId = n.GetStringValue(); } },
                { "hostname", n => { Hostname = n.GetStringValue(); } },
                { "is_exempt_from_device_limits", n => { IsExemptFromDeviceLimits = n.GetBoolValue(); } },
                { "is_exempt_from_login_verification", n => { IsExemptFromLoginVerification = n.GetBoolValue(); } },
                { "is_external_collab_restricted", n => { IsExternalCollabRestricted = n.GetBoolValue(); } },
                { "is_platform_access_only", n => { IsPlatformAccessOnly = n.GetBoolValue(); } },
                { "is_sync_enabled", n => { IsSyncEnabled = n.GetBoolValue(); } },
                { "my_tags", n => { MyTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "role", n => { Role = n.GetEnumValue<global::Soenneker.Box.OpenApiClient.Models.UserFull_role>(); } },
                { "tracking_codes", n => { TrackingCodes = n.GetCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.TrackingCode>(global::Soenneker.Box.OpenApiClient.Models.TrackingCode.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("can_see_managed_users", CanSeeManagedUsers);
            writer.WriteObjectValue<global::Soenneker.Box.OpenApiClient.Models.UserFull_enterprise>("enterprise", Enterprise);
            writer.WriteStringValue("external_app_user_id", ExternalAppUserId);
            writer.WriteStringValue("hostname", Hostname);
            writer.WriteBoolValue("is_exempt_from_device_limits", IsExemptFromDeviceLimits);
            writer.WriteBoolValue("is_exempt_from_login_verification", IsExemptFromLoginVerification);
            writer.WriteBoolValue("is_external_collab_restricted", IsExternalCollabRestricted);
            writer.WriteBoolValue("is_platform_access_only", IsPlatformAccessOnly);
            writer.WriteBoolValue("is_sync_enabled", IsSyncEnabled);
            writer.WriteCollectionOfPrimitiveValues<string>("my_tags", MyTags);
            writer.WriteEnumValue<global::Soenneker.Box.OpenApiClient.Models.UserFull_role>("role", Role);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Box.OpenApiClient.Models.TrackingCode>("tracking_codes", TrackingCodes);
        }
    }
}
#pragma warning restore CS0618
