// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Box.OpenApiClient.Models
{
    /// <summary>The trigger&apos;s resource type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Workflow_flows_trigger_type
    {
        [EnumMember(Value = "trigger")]
        #pragma warning disable CS1591
        Trigger,
        #pragma warning restore CS1591
    }
}
