// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Box.OpenApiClient.Models;
using Soenneker.Box.OpenApiClient.Workflows.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Box.OpenApiClient.Workflows
{
    /// <summary>
    /// Builds and executes requests for operations under \workflows
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkflowsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Box.OpenApiClient.workflows.item collection</summary>
        /// <param name="position">The ID of the workflow.</param>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Workflows.Item.WithWorkflow_ItemRequestBuilder"/></returns>
        public global::Soenneker.Box.OpenApiClient.Workflows.Item.WithWorkflow_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("workflow_id", position);
                return new global::Soenneker.Box.OpenApiClient.Workflows.Item.WithWorkflow_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows?folder_id={folder_id}{&limit*,marker*,trigger_type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkflowsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workflows?folder_id={folder_id}{&limit*,marker*,trigger_type*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns list of workflows that act on a given `folder ID`, andhave a flow with a trigger type of `WORKFLOW_MANUAL_START`.You application must be authorized to use the `Manage Box Relay` applicationscope within the developer console in to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Models.Workflows"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Box.OpenApiClient.Models.ClientError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Workflows?> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder.WorkflowsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Box.OpenApiClient.Models.Workflows> GetAsync(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder.WorkflowsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Box.OpenApiClient.Models.ClientError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Box.OpenApiClient.Models.Workflows>(requestInfo, global::Soenneker.Box.OpenApiClient.Models.Workflows.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns list of workflows that act on a given `folder ID`, andhave a flow with a trigger type of `WORKFLOW_MANUAL_START`.You application must be authorized to use the `Manage Box Relay` applicationscope within the developer console in to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder.WorkflowsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder.WorkflowsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Box.OpenApiClient.Workflows.WorkflowsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns list of workflows that act on a given `folder ID`, andhave a flow with a trigger type of `WORKFLOW_MANUAL_START`.You application must be authorized to use the `Manage Box Relay` applicationscope within the developer console in to use this endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorkflowsRequestBuilderGetQueryParameters 
        {
            /// <summary>The unique identifier that represent a folder.The ID for any folder can be determinedby visiting this folder in the web applicationand copying the ID from the URL. For example,for the URL `https://*.app.box.com/folder/123`the `folder_id` is `123`.The root folder of a Box account isalways represented by the ID `0`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("folder_id")]
            public string? FolderId { get; set; }
#nullable restore
#else
            [QueryParameter("folder_id")]
            public string FolderId { get; set; }
#endif
            /// <summary>The maximum number of items to return per page.</summary>
            [QueryParameter("limit")]
            public long? Limit { get; set; }
            /// <summary>Defines the position marker at which to begin returning results. This isused when paginating using marker-based pagination.This requires `usemarker` to be set to `true`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("marker")]
            public string? Marker { get; set; }
#nullable restore
#else
            [QueryParameter("marker")]
            public string Marker { get; set; }
#endif
            /// <summary>Type of trigger to search for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("trigger_type")]
            public string? TriggerType { get; set; }
#nullable restore
#else
            [QueryParameter("trigger_type")]
            public string TriggerType { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
